# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 18e7005
_src_path: gh:scipp/copier_template
description: An h5py-like utility for NeXus files with seamless Scipp integration
max_python: '3.13'
min_python: '3.10'
namespace_package: ''
nightly_deps: scipp
orgname: scipp
prettyname: ScippNexus
projectname: scippnexus
related_projects: Scipp,ScippNeutron
year: 2025
