package:
  name: scippnexus

  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..


{% set pyproject = load_file_data('pyproject.toml') %}
{% set dependencies = pyproject.get('project', {}).get('dependencies', {}) %}


requirements:
  build:
    - setuptools
    - setuptools_scm
  run:
    - python>=3.9

  {% for package in dependencies %}
    - {% if package == "graphviz" %}python-graphviz{% else %}{{ package }}{% endif %}
  {% endfor %}


test:
  imports:
    - scippnexus
  requires:
    - pytest
  source_files:
    - pyproject.toml
    - tests/
  commands:
    # We ignore warnings during release package builds
    - python -m pytest -Wignore tests

build:
  noarch: python
  script:
    - python -m pip install .

about:
  home: https://github.com/scipp/scippnexus
  license: BSD-3-Clause
  summary: An h5py-like utility for NeXus files with seamless Scipp integration
  description: An h5py-like utility for NeXus files with seamless Scipp integration
  dev_url: https://github.com/scipp/scippnexus
  doc_url: https://scipp.github.io/scippnexus
